# Generated by Django 4.2.9 on 2024-06-10 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_remove_shipment_package_details_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("settlement_local_currency", models.CharField(max_length=3)),
                ("settlement_foreign_currency", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="ContactInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "mobile_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("full_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ImageOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_code", models.CharField(max_length=10)),
                ("template_name", models.CharField(max_length=100)),
                ("is_requested", models.BooleanField()),
                (
                    "invoice_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "language_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "language_country_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "language_script_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("encoding_format", models.CharField(max_length=10)),
                ("render_dhl_logo", models.BooleanField()),
                ("fit_labels_to_a4", models.BooleanField()),
                (
                    "label_free_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "label_customer_data_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipment_receipt_customer_data_text",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostalAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postal_code", models.CharField(max_length=12)),
                ("city_name", models.CharField(max_length=45)),
                ("country_code", models.CharField(max_length=2)),
                (
                    "province_code",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                ("address_line1", models.CharField(max_length=100)),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "address_line3",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("county_name", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "province_name",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                (
                    "country_name",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistrationNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_code", models.CharField(max_length=10)),
                ("number", models.CharField(max_length=20)),
                ("issuer_country_code", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="ValueAddedService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_code", models.CharField(max_length=10)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=3)),
                ("method", models.CharField(blank=True, max_length=10, null=True)),
                ("dangerous_goods", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="shipment",
            name="get_rate_estimates",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="local_product_code",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="pickup_is_requested",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="product_code",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="OutputImageProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("printer_dpi", models.IntegerField()),
                ("encoding_format", models.CharField(max_length=10)),
                ("split_transport_and_waybill_doc_labels", models.BooleanField()),
                ("all_documents_in_one_image", models.BooleanField()),
                ("split_documents_by_pages", models.BooleanField()),
                ("split_invoice_and_receipt", models.BooleanField()),
                ("receipt_and_labels_in_one_image", models.BooleanField()),
                ("image_options", models.ManyToManyField(to="app.imageoption")),
            ],
        ),
        migrations.CreateModel(
            name="CustomerDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_code", models.CharField(max_length=10)),
                ("bank_details", models.ManyToManyField(to="app.bankdetail")),
                (
                    "contact_information",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.contactinformation",
                    ),
                ),
                (
                    "postal_address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.postaladdress",
                    ),
                ),
                (
                    "registration_numbers",
                    models.ManyToManyField(to="app.registrationnumber"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shipment",
            name="customer_details",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.customerdetails",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="output_image_properties",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.outputimageproperty",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="value_added_services",
            field=models.ManyToManyField(to="app.valueaddedservice"),
        ),
    ]
