# Generated by Django 4.2.9 on 2024-06-10 21:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_bankdetail_contactinformation_imageoption_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="customer_details",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="get_rate_estimates",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="local_product_code",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="output_image_properties",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="pickup_is_requested",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="product_code",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="value_added_services",
        ),
    ]
