# Generated by Django 4.2.9 on 2024-06-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("info", models.CharField(default="", max_length=100)),
                ("price", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShipmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_to_account", models.CharField(max_length=50)),
                ("contents", models.CharField(max_length=255)),
                ("destination_airport_code", models.CharField(max_length=10)),
                ("facility_id", models.CharField(max_length=10)),
                ("licence_plate_no", models.CharField(max_length=50)),
                ("outbound_mail_sort_code", models.CharField(max_length=10)),
                ("plt", models.BooleanField()),
                ("product_abbreviation", models.CharField(max_length=10)),
                (
                    "receiver_address_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "receiver_address_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "receiver_address_3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "receiver_business_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("receiver_city", models.CharField(max_length=50)),
                ("receiver_country", models.CharField(max_length=50)),
                ("receiver_name", models.CharField(max_length=50)),
                (
                    "receiver_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "receiver_postcode_zip",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("shipper_address_1", models.CharField(max_length=255)),
                ("shipper_address_2", models.CharField(max_length=255)),
                ("shipper_address_3", models.CharField(max_length=255)),
                ("shipper_airport_code", models.CharField(max_length=10)),
                ("shipper_city", models.CharField(max_length=50)),
                ("shipper_company_name", models.CharField(max_length=255)),
                ("shipper_country", models.CharField(max_length=50)),
                ("shipper_name", models.CharField(max_length=50)),
                ("shipper_phone", models.CharField(max_length=50)),
                ("shipper_postcode_zip", models.CharField(max_length=20)),
                (
                    "weight_rounded",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
    ]
