# Generated by Django 4.2.9 on 2024-06-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmenthistory",
            name="reciever_attention",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
