# Generated by Django 4.2.9 on 2024-06-24 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_shipmenthistory_reciever_attention"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmenthistory",
            name="reciever_company_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shipmenthistory",
            name="reciever_country_code",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="shipmenthistory",
            name="reciever_telephone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="shipmenthistory",
            name="shipment_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipmenthistory",
            name="shipment_declared_value",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipmenthistory",
            name="shipment_id",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipmenthistory",
            name="shipment_pieces",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipmenthistory",
            name="shipment_reference",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipmenthistory",
            name="shipment_weight",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipmenthistory",
            name="shipper_account_number",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shipmenthistory",
            name="receiver_city",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="shipmenthistory",
            name="receiver_country",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="shipmenthistory",
            name="receiver_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
